name: UMI KSU Kernel
run-name: UMI KSU Kernel

on:
  push:
    branches: [ base ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nexgang/ubuntu:latest

    steps:
      - uses: actions/checkout@v3
      - name: Umi KSU Kernel
        run: bash munch.sh null null
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
